### ISSUE TITLE
[REWRITE] TODO

### ISSUE THREAD

**Issue by cheesycod** [LunarsDev/fates-rewrite#3]
- [] Implement search (Partially done)
- [] Add/edit bot
- [] Profile page
- [] Profile settings page
- [] Partner pages
- [] Developer API (Partially done)
- [X] Basic project structure and core basic endpoints
